// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6QBTU3VU9pDajCh0DMIqu4sRJGfk1XI',
    appId: '1:910780290985:web:ba4c04ed590104d8ebd6b8',
    messagingSenderId: '910780290985',
    projectId: 'zoom-clone-907a2',
    authDomain: 'zoom-clone-907a2.firebaseapp.com',
    storageBucket: 'zoom-clone-907a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcAnWLtumhnkRJOwwyDHGj4wbI1kwWzI',
    appId: '1:910780290985:android:2921a81951eced52ebd6b8',
    messagingSenderId: '910780290985',
    projectId: 'zoom-clone-907a2',
    storageBucket: 'zoom-clone-907a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8j06yirEeTiWY6Iqz5NoaCQw0xwRwaL4',
    appId: '1:910780290985:ios:13b245bd1393d74febd6b8',
    messagingSenderId: '910780290985',
    projectId: 'zoom-clone-907a2',
    storageBucket: 'zoom-clone-907a2.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8j06yirEeTiWY6Iqz5NoaCQw0xwRwaL4',
    appId: '1:910780290985:ios:13b245bd1393d74febd6b8',
    messagingSenderId: '910780290985',
    projectId: 'zoom-clone-907a2',
    storageBucket: 'zoom-clone-907a2.firebasestorage.app',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT6QBTU3VU9pDajCh0DMIqu4sRJGfk1XI',
    appId: '1:910780290985:web:859233f9513f45bbebd6b8',
    messagingSenderId: '910780290985',
    projectId: 'zoom-clone-907a2',
    authDomain: 'zoom-clone-907a2.firebaseapp.com',
    storageBucket: 'zoom-clone-907a2.firebasestorage.app',
  );
}
